services:
  postgres:
    image: postgres:16
    container_name: support_postgres
    environment:
      POSTGRES_USER: support_user
      POSTGRES_PASSWORD: support_password
      POSTGRES_DB: support_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: support_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # management UI
    environment:
      RABBITMQ_DEFAULT_USER: support_user
      RABBITMQ_DEFAULT_PASS: support_password

  qdrant:
    image: qdrant/qdrant
    container_name: support_qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  postgres_data:
  qdrant_data:
